### ISSUE TITLE
Giriş butonu Tasarım ve Event

### ISSUE THREAD

**Issue by turakahmet** [teamoftarnet/androidMobil#15]
Girş butonuna basıldıktan sonra ekrana 
kullanıcı adı ve
kullanıcı parola soran bir pop up ekranı gelmesi bu ekranda 
2 adet textbox
3 adet button 
1 adet label button olmalı

Tasarım: resimdeki gibi benzer olabilir 
https://i.imgur.com/a63OjXh.png

**Comment by turakahmet** [comment]
Giriş butonu artık mekan kayıt etmek için kullanıyor. Buna gerek kalmadı

**Comment by efealigulocak** [comment]
tab3de aktiftir.
