### ISSUE TITLE
Üye ol button event

### ISSUE THREAD

**Issue by turakahmet** [teamoftarnet/androidMobil#19]
Tab 2de bulunan üye ol butonuna basarak bir popup ekranı ile kullanıcılardan gerekli bilgiler alınarak üye olunması gerekir. 
popup ekranında ise veritabanımızda user ile ilgili istenen bilgilere göre gerekli textboxlar textviewler
ve butonlar oluşturularak buton yardımıyla bu bilgiler db ye post edilir. 
Aynı işlemler direk listeyi doldurmadan Gmail veya facebook api servislerine bağlanılarak buradaki bilgiler alınıp oracle db ye gönderilir.
Dikkat edilmesi gereken butona basıldıktan sonra
Kullanıcıdan mail adresini alınmalı ve veri tabanınında aynı mail adresi ile kayıt olmak isteyenlere log mesajı basılmasıdır.

**Comment by efealigulocak** [comment]
İlgili işler yapılmıştır.
