### ISSUE TITLE
Tab2 buton eventları

### ISSUE THREAD

**Issue by turakahmet** [teamoftarnet/androidMobil#20]
Tab 2 de bulunan 
En Yüksek Puanlı Mekanlar
Temizlik Dostu Mekanlar
Çocuk Dostu Mekanlar
butonlarına basılması halinde tab1 alanına ekranın kayması ve bu alanda query işlemi yapıldıktan sonra gerekli restoranların 10 arlı şekilde çıkması

**Comment by efealigulocak** [comment]
İlgili işler yapılmıştır.
