### ISSUE TITLE
Tab1 mekan puanlama verileri

### ISSUE THREAD

**Issue by turakahmet** [teamoftarnet/androidMobil#32]
Bildiğiniz üzere puanlama yapabiliyoruz fakat restoranıd ve userıd şuan manuel olarak kod içresinde girilmekte.
Bunun yerine cardview tıklanıldığında o restorana ait ıd numarasını sistem almalı ve yine aynı şekilde giriş yapan kullanıcının da user idsi alınıp bunlar post işleminde manuel olan yerlerde kullanılmalı.
Bu sayede kullanıcı direk tıkladığı cardview restoranıd ve user ıd bilgilerine alarak puanlama yapabilmeli.

**Comment by efealigulocak** [comment]
ilgili işler yapılmıştır
